# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d668c1893731088c7ea6489a457a0cc0021b2b3981ddd6cbaa179fff753f529d81ec07dc02ba456693deaa6f5eb98003c89ec0cb21bd34543cc7bdc4e1c4bab3

test:
  secret_key_base: 91fc27c61014f0209f8870ead8918d845193bafb0d4476563cb8c7ce1da3016a9ec0ddc7c90e8a4fb69b386ebfdab5781e59d93dcf2e5c2e2948fcf3588ea8ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
